import './globals.css';
import 'react-notion-x/src/styles.css';
import 'prismjs/themes/prism-tomorrow.css';
import 'katex/dist/katex.min.css';

import Footer from '@/components/ui/Footer';
import Header from '@/components/ui/Header';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { NotionAPI } from 'notion-client';
import SiteConfig from '~/site.config';

const notion = new NotionAPI();

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const recordMap = await notion.getPage(SiteConfig.rootNotionPageId);

  return (
    <html lang="kr">
      <body className={inter.className}>
        <Header>Gitsunmin Blog</Header>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
