import LayoutFooter from './layout/footer';
import LayoutHeader from './layout/header';
import LayoutMain from './layout/main';
import ProfileImage from './ui/profile-image';
import LabeledIcon from './ui/labeled-icon';
import SectionTitle from './ui/section-title';
import SectionWrapper from './ui/section-wrapper';
import HelloSection from './section/hello/section';
import AboutMeSection from './section/about_me/section';
import AboutMeScene1 from './section/about_me/scene1';
import SkillsSection from './section/skills/section';
import SkillsScene1 from './section/skills/scene1';
import ExperienceSection from './section/experience/section';
import ExperienceScene1 from './section/experience/scene1';

export const defineComponents = () => {
  customElements.define('profile-image', ProfileImage);
  customElements.define('labeled-icon', LabeledIcon);
  customElements.define('about-me-section', AboutMeSection);
  customElements.define('about-me-scene1', AboutMeScene1);
  customElements.define('section-title', SectionTitle);
  customElements.define('section-wrapper', SectionWrapper);
  customElements.define('layout-footer', LayoutFooter);
  customElements.define('layout-header', LayoutHeader);
  customElements.define('layout-main', LayoutMain);
  customElements.define('hello-section', HelloSection);
  customElements.define('skills-section', SkillsSection);
  customElements.define('skills-scene1', SkillsScene1);
  customElements.define('experience-section', ExperienceSection);
  customElements.define('experience-scene1', ExperienceScene1);
};
